#!/bin/busybox sh
# PID 1 inside the matrix VM.
#
# The guest has no distribution in it: the initramfs is a static busybox, the
# cross-compiled Go test binaries, and the handful of repository files the
# drift tests read. Everything this script mounts, the tests need:
#
#   /proc, /sys        cilium/ebpf reads /proc/sys/net/core/bpf_jit_enable and
#                      /sys/kernel/btf/vmlinux; the manager reads
#                      /proc/sys/kernel/unprivileged_bpf_disabled.
#   /dev (devtmpfs)    /dev/null and friends.
#   /tmp (tmpfs)       t.TempDir(). It must NOT be bpffs: the inspector tests
#                      assert what happens when a pin path is on the wrong
#                      filesystem, and a tmpfs is exactly that case.
#   /sys/fs/bpf        the pin root the manager pins into.
#   lo up              the attach tests build veth pairs in fresh netns.
#
# The VM always runs as root with everything: least-privilege is asserted by
# the CI job that runs the same binary under setpriv on the runner's own
# kernel. This harness answers a different question — does the KERNEL accept
# the program — so it deliberately removes capability as a variable.

/bin/busybox --install -s /bin 2>/dev/null
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount -t proc     proc     /proc
mount -t sysfs    sysfs    /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null
mount -t tmpfs    tmpfs    /tmp
mkdir -p /sys/fs/bpf && mount -t bpf bpf /sys/fs/bpf
ip link set lo up 2>/dev/null

# Environment facts first, so a failure below can be read without a rerun.
echo "KAPKAN_VM_KERNEL=$(uname -r) $(uname -m)"
if [ -r /sys/kernel/btf/vmlinux ]; then
	echo "KAPKAN_VM_BTF=yes bytes=$(wc -c < /sys/kernel/btf/vmlinux)"
else
	echo "KAPKAN_VM_BTF=no"
fi
echo "KAPKAN_VM_JIT=$(cat /proc/sys/net/core/bpf_jit_enable 2>/dev/null)"
echo "KAPKAN_VM_UNPRIV_BPF=$(cat /proc/sys/kernel/unprivileged_bpf_disabled 2>/dev/null)"

# run.conf is generated by boot.sh from the driver's environment. It defines
# FLAGS (go test flags) and RUNS (newline-separated "<binary> <workdir>").
FLAGS="-test.v"
RUNS=""
# shellcheck disable=SC1091  # generated into the initramfs by boot.sh.
[ -r /run.conf ] && . /run.conf

# The loop runs in this shell (no pipe) so KAPKAN_VM_RC lines are emitted from
# a process whose exit status is the test's, not a subshell's.
printf '%s\n' "$RUNS" > /tmp/runs
while read -r bin dir; do
	[ -z "$bin" ] && continue
	echo "KAPKAN_VM_RUN=$bin cwd=$dir"
	if ! cd "$dir" 2>/dev/null; then
		echo "KAPKAN_VM_RC=$bin 97"
		continue
	fi
	# shellcheck disable=SC2086  # FLAGS is a deliberate word-split list.
	"/$bin" $FLAGS
	echo "KAPKAN_VM_RC=$bin $?"
done < /tmp/runs

# The driver keys off this line: a kernel that panicked, or a test binary that
# took the machine down with it, never prints it, and that must not read as a
# pass.
echo "KAPKAN_VM_DONE=1"
sync
poweroff -f
