// Localized strings for the config builder, per locale. Every field shows a
// human label (wizardLabels) with the raw YAML key beside it — the key is what
// you write in the file and what the docs reference verbatim, the label says
// what the field does. Field help is localized in wizardHelp; EN help is not
// duplicated here: it falls back to the overlay's `description` (see helpText
// in ConfigBuilder).

import type { Locale } from "@/lib/i18n";

export type SectionId =
  | "telemetry"
  | "networks"
  | "detection"
  | "mitigation"
  | "bans"
  | "notify"
  | "api";

export type WizardValidation = {
  required: string;
  enum: string; // "{allowed}" placeholder
  identifier: string; // regex-pattern failure (env/db/group names)
  notNumber: string;
  min: string; // "{min}" placeholder
  max: string; // "{max}" placeholder
  formats: Record<string, string>; // keyed by overlay `format`: ipv4/ipv6/ip/cidr/hostport/community/url
};

export type WizardChrome = {
  title: string;
  intro: string;
  privacy: string;
  advanced: string;
  output: string;
  copy: string;
  copied: string;
  download: string;
  checkHint: string;
  docsCta: string;
  accepts: string; // engine-accepts strip label
  liveWarning: string;
  addItem: string;
  addNeighbor: string;
  nav: string; // aria-label of the section rail
  modeWatch: string; // watch-only pill label
  modeLive: string; // live pill label
  modeWatchDesc: string;
  fieldErrors: string; // "{n}" placeholder
  engineChecking: string;
  engineOff: string;
  engineSummary: string;
  yamlJump: string; // mobile anchor to the YAML pane
  minutes: string; // "{v}" placeholder — seconds-field gloss
  hours: string; // "{v}" placeholder
  sections: Record<SectionId, string>;
  subheads: {
    method: string;
    bgp: string;
    perProtocol: string;
    telegram: string;
    updates: string;
  };
  advHints: Partial<Record<SectionId, string>>;
  validation: WizardValidation;
};

export const wizardChrome: Record<Locale, WizardChrome> = {
  en: {
    title: "Config builder",
    intro: "Assemble a Kapkan configuration on one page — the YAML updates live as you type. Sensible, watch-only-safe defaults are filled in; adjust them to your network.",
    privacy: "Runs entirely in your browser. Nothing you enter is sent anywhere.",
    advanced: "Advanced",
    output: "config.yaml",
    copy: "Copy",
    copied: "Copied",
    download: "Download",
    checkHint: "Validate on your host before going live:",
    docsCta: "Configuration reference",
    accepts: "Engine accepts this config",
    liveWarning: "LIVE mode: real BGP blackhole announcements will be sent. Keep watch-only on until detection is validated.",
    addItem: "+ Add",
    addNeighbor: "+ Add neighbor",
    nav: "Config sections",
    modeWatch: "Watch-only",
    modeLive: "Live",
    modeWatchDesc: "Mitigation is simulated, nothing is announced — safe to experiment.",
    fieldErrors: "Field errors: {n}",
    engineChecking: "Engine check running…",
    engineOff: "Engine validator unavailable in this browser — inline schema checks still apply.",
    engineSummary: "Engine summary",
    yamlJump: "View YAML",
    minutes: "≈ {v} min",
    hours: "≈ {v} h",
    sections: {
      telemetry: "Telemetry",
      networks: "Protected networks",
      detection: "Detection",
      mitigation: "Mitigation",
      bans: "Bans",
      notify: "Notifications",
      api: "API",
    },
    subheads: {
      method: "Mitigation method",
      bgp: "BGP",
      perProtocol: "Per-protocol limits",
      telegram: "Telegram",
      updates: "Updates",
    },
    advHints: {
      detection: "TCP SYN / UDP limits",
      mitigation: "Graceful Restart",
      bans: "ban persistence",
      notify: "update check",
    },
    validation: {
      required: "required",
      enum: "must be one of: {allowed}",
      identifier: 'invalid value (allowed: letters, digits, "_", "-", ".")',
      notNumber: "must be a number",
      min: "must be ≥ {min}",
      max: "must be ≤ {max}",
      formats: {
        ipv4: "must be an IPv4 address (e.g. 192.0.2.1)",
        ipv6: "must be an IPv6 address (e.g. 2001:db8::1)",
        ip: "must be an IP address",
        cidr: "must be a CIDR prefix (e.g. 203.0.113.0/24)",
        hostport: "must be host:port (e.g. :6343 or 127.0.0.1:8080)",
        community: "must be a BGP community ASN:value (e.g. 65000:666)",
        url: "must be an http(s) URL",
      },
    },
  },
  ru: {
    title: "Конструктор конфигурации",
    intro: "Соберите конфиг Kapkan на одной странице — YAML обновляется по мере ввода. Безопасные значения по умолчанию (режим наблюдения) уже подставлены, подгоните их под свою сеть.",
    privacy: "Работает полностью в браузере. Ничего из введённого никуда не отправляется.",
    advanced: "Дополнительно",
    output: "config.yaml",
    copy: "Копировать",
    copied: "Скопировано",
    download: "Скачать",
    checkHint: "Проверьте на своём хосте перед боевым запуском:",
    docsCta: "Справочник конфигурации",
    accepts: "Движок принимает этот конфиг",
    liveWarning: "Боевой режим: реальные BGP-анонсы blackhole будут отправлены. Держите режим наблюдения, пока детект не выверен.",
    addItem: "+ Добавить",
    addNeighbor: "+ Добавить соседа",
    nav: "Секции конфига",
    modeWatch: "Только наблюдение",
    modeLive: "Боевой режим",
    modeWatchDesc: "Подавление имитируется, анонсы не отправляются — можно спокойно экспериментировать.",
    fieldErrors: "Ошибки в полях: {n}",
    engineChecking: "Проверка движком…",
    engineOff: "Валидатор движка недоступен в этом браузере — работают только проверки по схеме.",
    engineSummary: "Сводка движка",
    yamlJump: "К YAML",
    minutes: "≈ {v} мин",
    hours: "≈ {v} ч",
    sections: {
      telemetry: "Телеметрия",
      networks: "Защищаемые сети",
      detection: "Обнаружение",
      mitigation: "Подавление",
      bans: "Баны",
      notify: "Уведомления",
      api: "API",
    },
    subheads: {
      method: "Метод подавления",
      bgp: "BGP",
      perProtocol: "Лимиты по протоколам",
      telegram: "Telegram",
      updates: "Обновления",
    },
    advHints: {
      detection: "лимиты TCP SYN / UDP",
      mitigation: "Graceful Restart",
      bans: "персистентность банов",
      notify: "проверка обновлений",
    },
    validation: {
      required: "обязательно",
      enum: "должно быть одним из: {allowed}",
      identifier: 'недопустимое значение (разрешены: буквы, цифры, "_", "-", ".")',
      notNumber: "должно быть числом",
      min: "должно быть ≥ {min}",
      max: "должно быть ≤ {max}",
      formats: {
        ipv4: "должно быть IPv4-адресом (напр. 192.0.2.1)",
        ipv6: "должно быть IPv6-адресом (напр. 2001:db8::1)",
        ip: "должно быть IP-адресом",
        cidr: "должно быть CIDR-префиксом (напр. 203.0.113.0/24)",
        hostport: "должно быть host:port (напр. :6343 или 127.0.0.1:8080)",
        community: "должно быть BGP-community вида ASN:value (напр. 65000:666)",
        url: "должно быть http(s)-URL",
      },
    },
  },
  de: {
    title: "Konfigurations-Builder",
    intro: "Erstellen Sie eine Kapkan-Konfiguration auf einer Seite — das YAML aktualisiert sich live beim Tippen. Sichere Standardwerte (Beobachtungsmodus) sind vorausgefüllt; passen Sie sie an Ihr Netz an.",
    privacy: "Läuft vollständig im Browser. Nichts von dem, was Sie eingeben, wird übertragen.",
    advanced: "Erweitert",
    output: "config.yaml",
    copy: "Kopieren",
    copied: "Kopiert",
    download: "Herunterladen",
    checkHint: "Vor dem Live-Betrieb auf Ihrem Host prüfen:",
    docsCta: "Konfigurationsreferenz",
    accepts: "Engine akzeptiert diese Konfiguration",
    liveWarning: "LIVE-Modus: echte BGP-Blackhole-Ankündigungen werden gesendet. Bleiben Sie im Beobachtungsmodus, bis die Erkennung validiert ist.",
    addItem: "+ Hinzufügen",
    addNeighbor: "+ Nachbarn hinzufügen",
    nav: "Konfigurationsabschnitte",
    modeWatch: "Nur beobachten",
    modeLive: "Live",
    modeWatchDesc: "Mitigation wird simuliert, nichts wird angekündigt — gefahrloses Experimentieren.",
    fieldErrors: "Feldfehler: {n}",
    engineChecking: "Engine-Prüfung läuft…",
    engineOff: "Engine-Validator in diesem Browser nicht verfügbar — Schema-Prüfungen gelten weiterhin.",
    engineSummary: "Engine-Übersicht",
    yamlJump: "Zum YAML",
    minutes: "≈ {v} Min.",
    hours: "≈ {v} Std.",
    sections: {
      telemetry: "Telemetrie",
      networks: "Geschützte Netze",
      detection: "Erkennung",
      mitigation: "Mitigation",
      bans: "Bans",
      notify: "Benachrichtigungen",
      api: "API",
    },
    subheads: {
      method: "Mitigationsmethode",
      bgp: "BGP",
      perProtocol: "Limits pro Protokoll",
      telegram: "Telegram",
      updates: "Updates",
    },
    advHints: {
      detection: "TCP-SYN-/UDP-Limits",
      mitigation: "Graceful Restart",
      bans: "Ban-Persistenz",
      notify: "Update-Prüfung",
    },
    validation: {
      required: "erforderlich",
      enum: "muss eines von: {allowed} sein",
      identifier: 'ungültiger Wert (erlaubt: Buchstaben, Ziffern, "_", "-", ".")',
      notNumber: "muss eine Zahl sein",
      min: "muss ≥ {min} sein",
      max: "muss ≤ {max} sein",
      formats: {
        ipv4: "muss eine IPv4-Adresse sein (z. B. 192.0.2.1)",
        ipv6: "muss eine IPv6-Adresse sein (z. B. 2001:db8::1)",
        ip: "muss eine IP-Adresse sein",
        cidr: "muss ein CIDR-Präfix sein (z. B. 203.0.113.0/24)",
        hostport: "muss host:port sein (z. B. :6343 oder 127.0.0.1:8080)",
        community: "muss eine BGP-Community ASN:Wert sein (z. B. 65000:666)",
        url: "muss eine http(s)-URL sein",
      },
    },
  },
  fr: {
    title: "Générateur de configuration",
    intro: "Composez une configuration Kapkan sur une seule page — le YAML se met à jour pendant la saisie. Des valeurs par défaut sûres (mode observation) sont pré-remplies ; adaptez-les à votre réseau.",
    privacy: "Fonctionne entièrement dans votre navigateur. Rien de ce que vous saisissez n'est envoyé.",
    advanced: "Avancé",
    output: "config.yaml",
    copy: "Copier",
    copied: "Copié",
    download: "Télécharger",
    checkHint: "Validez sur votre hôte avant la mise en production :",
    docsCta: "Référence de configuration",
    accepts: "Le moteur accepte cette configuration",
    liveWarning: "Mode LIVE : de vraies annonces BGP blackhole seront envoyées. Restez en observation jusqu'à validation de la détection.",
    addItem: "+ Ajouter",
    addNeighbor: "+ Ajouter un voisin",
    nav: "Sections de configuration",
    modeWatch: "Observation seule",
    modeLive: "Live",
    modeWatchDesc: "L'atténuation est simulée, rien n'est annoncé — expérimentez sans risque.",
    fieldErrors: "Erreurs de champs : {n}",
    engineChecking: "Vérification moteur…",
    engineOff: "Validateur du moteur indisponible dans ce navigateur — les contrôles de schéma restent actifs.",
    engineSummary: "Résumé du moteur",
    yamlJump: "Voir le YAML",
    minutes: "≈ {v} min",
    hours: "≈ {v} h",
    sections: {
      telemetry: "Télémétrie",
      networks: "Réseaux protégés",
      detection: "Détection",
      mitigation: "Atténuation",
      bans: "Bans",
      notify: "Notifications",
      api: "API",
    },
    subheads: {
      method: "Méthode d'atténuation",
      bgp: "BGP",
      perProtocol: "Limites par protocole",
      telegram: "Telegram",
      updates: "Mises à jour",
    },
    advHints: {
      detection: "limites TCP SYN / UDP",
      mitigation: "Graceful Restart",
      bans: "persistance des bans",
      notify: "vérification des mises à jour",
    },
    validation: {
      required: "requis",
      enum: "doit être l'un de : {allowed}",
      identifier: 'valeur invalide (autorisés : lettres, chiffres, "_", "-", ".")',
      notNumber: "doit être un nombre",
      min: "doit être ≥ {min}",
      max: "doit être ≤ {max}",
      formats: {
        ipv4: "doit être une adresse IPv4 (p. ex. 192.0.2.1)",
        ipv6: "doit être une adresse IPv6 (p. ex. 2001:db8::1)",
        ip: "doit être une adresse IP",
        cidr: "doit être un préfixe CIDR (p. ex. 203.0.113.0/24)",
        hostport: "doit être host:port (p. ex. :6343 ou 127.0.0.1:8080)",
        community: "doit être une communauté BGP ASN:valeur (p. ex. 65000:666)",
        url: "doit être une URL http(s)",
      },
    },
  },
  es: {
    title: "Generador de configuración",
    intro: "Arma una configuración de Kapkan en una sola página — el YAML se actualiza en vivo mientras escribes. Se rellenan valores por defecto seguros (modo observación); ajústalos a tu red.",
    privacy: "Se ejecuta por completo en tu navegador. Nada de lo que introduces se envía a ningún sitio.",
    advanced: "Avanzado",
    output: "config.yaml",
    copy: "Copiar",
    copied: "Copiado",
    download: "Descargar",
    checkHint: "Valida en tu host antes de pasar a producción:",
    docsCta: "Referencia de configuración",
    accepts: "El motor acepta esta configuración",
    liveWarning: "Modo LIVE: se enviarán anuncios BGP blackhole reales. Mantén el modo observación hasta validar la detección.",
    addItem: "+ Añadir",
    addNeighbor: "+ Añadir vecino",
    nav: "Secciones de configuración",
    modeWatch: "Solo observación",
    modeLive: "Live",
    modeWatchDesc: "La mitigación se simula, nada se anuncia — experimenta sin riesgo.",
    fieldErrors: "Errores de campos: {n}",
    engineChecking: "Comprobación del motor…",
    engineOff: "Validador del motor no disponible en este navegador — siguen activas las comprobaciones de esquema.",
    engineSummary: "Resumen del motor",
    yamlJump: "Ver YAML",
    minutes: "≈ {v} min",
    hours: "≈ {v} h",
    sections: {
      telemetry: "Telemetría",
      networks: "Redes protegidas",
      detection: "Detección",
      mitigation: "Mitigación",
      bans: "Baneos",
      notify: "Notificaciones",
      api: "API",
    },
    subheads: {
      method: "Método de mitigación",
      bgp: "BGP",
      perProtocol: "Límites por protocolo",
      telegram: "Telegram",
      updates: "Actualizaciones",
    },
    advHints: {
      detection: "límites TCP SYN / UDP",
      mitigation: "Graceful Restart",
      bans: "persistencia de baneos",
      notify: "comprobación de actualizaciones",
    },
    validation: {
      required: "obligatorio",
      enum: "debe ser uno de: {allowed}",
      identifier: 'valor no válido (permitidos: letras, dígitos, "_", "-", ".")',
      notNumber: "debe ser un número",
      min: "debe ser ≥ {min}",
      max: "debe ser ≤ {max}",
      formats: {
        ipv4: "debe ser una dirección IPv4 (p. ej. 192.0.2.1)",
        ipv6: "debe ser una dirección IPv6 (p. ej. 2001:db8::1)",
        ip: "debe ser una dirección IP",
        cidr: "debe ser un prefijo CIDR (p. ej. 203.0.113.0/24)",
        hostport: "debe ser host:port (p. ej. :6343 o 127.0.0.1:8080)",
        community: "debe ser una comunidad BGP ASN:valor (p. ej. 65000:666)",
        url: "debe ser una URL http(s)",
      },
    },
  },
};

// Human field labels, keyed by yaml path. The raw key is shown beside the
// label in the UI, so labels describe the effect, not the syntax. EN is the
// fallback for any locale that misses a key.
export const wizardLabels: Record<Locale, Record<string, string>> = {
  en: {
    "listen.sflow": "sFlow listen address",
    "listen.netflow": "NetFlow / IPFIX listen address",
    "sampling.default_rate": "Default sampling rate",
    networks: "Protected prefixes",
    protected_whitelist: "Never-ban addresses",
    "thresholds.pps": "Packets per second",
    "thresholds.mbps": "Megabits per second",
    "thresholds.flows_per_sec": "Flows per second",
    "thresholds.tcp_syn_pps": "Pure TCP SYN packets/s",
    "thresholds.udp_pps": "UDP packets/s",
    mitigation: "Default method",
    "bgp.local_asn": "Local ASN",
    "bgp.router_id": "Router ID",
    "bgp.next_hop": "Blackhole next-hop (IPv4)",
    "bgp.next_hop6": "Blackhole next-hop (IPv6)",
    "bgp.community": "RTBH community",
    "bgp.neighbors": "Neighbors",
    "bgp.graceful_restart.enabled": "Graceful Restart",
    "bgp.graceful_restart.restart_seconds": "Restart hold time",
    "bgp.graceful_restart.long_lived": "Long-Lived GR (RFC 9494)",
    "bgp.graceful_restart.long_lived_stale_seconds": "LLGR stale time",
    "ban.ttl_seconds": "Ban lifetime",
    "ban.unban_hysteresis_seconds": "Unban hysteresis",
    "ban.max_active_bans": "Max simultaneous bans",
    "ban.state_file": "Ban state file",
    "notify.telegram.token_env": "Bot token env var",
    "notify.telegram.chat_id": "Chat ID",
    "update_check.enabled": "Check for updates",
    "update_check.interval_seconds": "Check interval",
    "update_check.channel": "Release channel",
    "update_check.url": "Releases endpoint override",
    "update_check.notify": "Notify about updates",
    "api.listen": "API listen address",
    "api.token_env": "API token env var",
  },
  ru: {
    "listen.sflow": "Адрес приёма sFlow",
    "listen.netflow": "Адрес приёма NetFlow / IPFIX",
    "sampling.default_rate": "Частота сэмплирования по умолчанию",
    networks: "Защищаемые префиксы",
    protected_whitelist: "Никогда не банить",
    "thresholds.pps": "Пакетов в секунду",
    "thresholds.mbps": "Мегабит в секунду",
    "thresholds.flows_per_sec": "Потоков в секунду",
    "thresholds.tcp_syn_pps": "Чистых TCP SYN пакетов/с",
    "thresholds.udp_pps": "UDP-пакетов/с",
    mitigation: "Метод по умолчанию",
    "bgp.local_asn": "Локальный ASN",
    "bgp.router_id": "Router ID",
    "bgp.next_hop": "Next-hop для blackhole (IPv4)",
    "bgp.next_hop6": "Next-hop для blackhole (IPv6)",
    "bgp.community": "RTBH-community",
    "bgp.neighbors": "Соседи",
    "bgp.graceful_restart.enabled": "Graceful Restart",
    "bgp.graceful_restart.restart_seconds": "Удержание при рестарте",
    "bgp.graceful_restart.long_lived": "Long-Lived GR (RFC 9494)",
    "bgp.graceful_restart.long_lived_stale_seconds": "Stale-время LLGR",
    "ban.ttl_seconds": "Время жизни бана",
    "ban.unban_hysteresis_seconds": "Гистерезис разбана",
    "ban.max_active_bans": "Максимум одновременных банов",
    "ban.state_file": "Файл состояния банов",
    "notify.telegram.token_env": "Env-переменная с токеном бота",
    "notify.telegram.chat_id": "ID чата",
    "update_check.enabled": "Проверять обновления",
    "update_check.interval_seconds": "Интервал проверки",
    "update_check.channel": "Канал релизов",
    "update_check.url": "Свой endpoint релизов",
    "update_check.notify": "Уведомлять об обновлениях",
    "api.listen": "Адрес API",
    "api.token_env": "Env-переменная API-токена",
  },
  de: {
    "listen.sflow": "sFlow-Empfangsadresse",
    "listen.netflow": "NetFlow-/IPFIX-Empfangsadresse",
    "sampling.default_rate": "Standard-Sampling-Rate",
    networks: "Geschützte Präfixe",
    protected_whitelist: "Nie bannen",
    "thresholds.pps": "Pakete pro Sekunde",
    "thresholds.mbps": "Megabit pro Sekunde",
    "thresholds.flows_per_sec": "Flows pro Sekunde",
    "thresholds.tcp_syn_pps": "Reine TCP-SYN-Pakete/s",
    "thresholds.udp_pps": "UDP-Pakete/s",
    mitigation: "Standardmethode",
    "bgp.local_asn": "Lokale ASN",
    "bgp.router_id": "Router-ID",
    "bgp.next_hop": "Blackhole-Next-Hop (IPv4)",
    "bgp.next_hop6": "Blackhole-Next-Hop (IPv6)",
    "bgp.community": "RTBH-Community",
    "bgp.neighbors": "Nachbarn",
    "bgp.graceful_restart.enabled": "Graceful Restart",
    "bgp.graceful_restart.restart_seconds": "Haltezeit beim Neustart",
    "bgp.graceful_restart.long_lived": "Long-Lived GR (RFC 9494)",
    "bgp.graceful_restart.long_lived_stale_seconds": "LLGR-Stale-Zeit",
    "ban.ttl_seconds": "Ban-Lebensdauer",
    "ban.unban_hysteresis_seconds": "Unban-Hysterese",
    "ban.max_active_bans": "Max. gleichzeitige Bans",
    "ban.state_file": "Ban-Statusdatei",
    "notify.telegram.token_env": "Env-Variable mit Bot-Token",
    "notify.telegram.chat_id": "Chat-ID",
    "update_check.enabled": "Auf Updates prüfen",
    "update_check.interval_seconds": "Prüfintervall",
    "update_check.channel": "Release-Kanal",
    "update_check.url": "Eigener Releases-Endpunkt",
    "update_check.notify": "Über Updates benachrichtigen",
    "api.listen": "API-Adresse",
    "api.token_env": "Env-Variable des API-Tokens",
  },
  fr: {
    "listen.sflow": "Adresse d'écoute sFlow",
    "listen.netflow": "Adresse d'écoute NetFlow / IPFIX",
    "sampling.default_rate": "Taux d'échantillonnage par défaut",
    networks: "Préfixes protégés",
    protected_whitelist: "Ne jamais bannir",
    "thresholds.pps": "Paquets par seconde",
    "thresholds.mbps": "Mégabits par seconde",
    "thresholds.flows_per_sec": "Flux par seconde",
    "thresholds.tcp_syn_pps": "Paquets TCP SYN purs/s",
    "thresholds.udp_pps": "Paquets UDP/s",
    mitigation: "Méthode par défaut",
    "bgp.local_asn": "ASN local",
    "bgp.router_id": "Router ID",
    "bgp.next_hop": "Next-hop blackhole (IPv4)",
    "bgp.next_hop6": "Next-hop blackhole (IPv6)",
    "bgp.community": "Communauté RTBH",
    "bgp.neighbors": "Voisins",
    "bgp.graceful_restart.enabled": "Graceful Restart",
    "bgp.graceful_restart.restart_seconds": "Temps de maintien au redémarrage",
    "bgp.graceful_restart.long_lived": "Long-Lived GR (RFC 9494)",
    "bgp.graceful_restart.long_lived_stale_seconds": "Temps stale LLGR",
    "ban.ttl_seconds": "Durée de vie du ban",
    "ban.unban_hysteresis_seconds": "Hystérésis de débannissement",
    "ban.max_active_bans": "Bans simultanés max",
    "ban.state_file": "Fichier d'état des bans",
    "notify.telegram.token_env": "Variable d'env. du token du bot",
    "notify.telegram.chat_id": "ID du chat",
    "update_check.enabled": "Vérifier les mises à jour",
    "update_check.interval_seconds": "Intervalle de vérification",
    "update_check.channel": "Canal de versions",
    "update_check.url": "Endpoint des releases personnalisé",
    "update_check.notify": "Notifier les mises à jour",
    "api.listen": "Adresse de l'API",
    "api.token_env": "Variable d'env. du token API",
  },
  es: {
    "listen.sflow": "Dirección de escucha sFlow",
    "listen.netflow": "Dirección de escucha NetFlow / IPFIX",
    "sampling.default_rate": "Tasa de muestreo por defecto",
    networks: "Prefijos protegidos",
    protected_whitelist: "Nunca banear",
    "thresholds.pps": "Paquetes por segundo",
    "thresholds.mbps": "Megabits por segundo",
    "thresholds.flows_per_sec": "Flujos por segundo",
    "thresholds.tcp_syn_pps": "Paquetes TCP SYN puros/s",
    "thresholds.udp_pps": "Paquetes UDP/s",
    mitigation: "Método por defecto",
    "bgp.local_asn": "ASN local",
    "bgp.router_id": "Router ID",
    "bgp.next_hop": "Next-hop de blackhole (IPv4)",
    "bgp.next_hop6": "Next-hop de blackhole (IPv6)",
    "bgp.community": "Comunidad RTBH",
    "bgp.neighbors": "Vecinos",
    "bgp.graceful_restart.enabled": "Graceful Restart",
    "bgp.graceful_restart.restart_seconds": "Retención al reiniciar",
    "bgp.graceful_restart.long_lived": "Long-Lived GR (RFC 9494)",
    "bgp.graceful_restart.long_lived_stale_seconds": "Tiempo stale de LLGR",
    "ban.ttl_seconds": "Vida del baneo",
    "ban.unban_hysteresis_seconds": "Histéresis de desbaneo",
    "ban.max_active_bans": "Baneos simultáneos máx.",
    "ban.state_file": "Archivo de estado de baneos",
    "notify.telegram.token_env": "Variable de entorno del token del bot",
    "notify.telegram.chat_id": "ID del chat",
    "update_check.enabled": "Comprobar actualizaciones",
    "update_check.interval_seconds": "Intervalo de comprobación",
    "update_check.channel": "Canal de versiones",
    "update_check.url": "Endpoint de releases propio",
    "update_check.notify": "Notificar actualizaciones",
    "api.listen": "Dirección de la API",
    "api.token_env": "Variable de entorno del token de la API",
  },
};

// Localized field help, keyed by yaml path. EN is intentionally absent — it
// falls back to the overlay's `description` (the single English source).
export const wizardHelp: Partial<Record<Locale, Record<string, string>>> = {
  ru: {
    dry_run: "Если включено (по умолчанию, в т.ч. при отсутствии ключа), митигация имитируется и никогда не анонсируется. Держите включённым, пока детект не выверен на живой телеметрии.",
    "listen.sflow": 'UDP-адрес для приёма sFlow, напр. ":6343". Нужен хотя бы один из sflow/netflow.',
    "listen.netflow": 'UDP-адрес для NetFlow v5/v9 и IPFIX (общий сокет), напр. ":2055".',
    "sampling.default_rate": "Частота сэмплирования, когда экспортёр не сообщает свою. Ошибка здесь масштабирует ВСЕ пороги — ставьте значение, которое реально экспортируют роутеры.",
    networks: "Защищаемые префиксы. Детект применяется только внутри них; они не должны пересекаться.",
    protected_whitelist: "Адреса, которые никогда не банятся независимо от трафика (шлюзы, NS).",
    "thresholds.pps": "Порог пакетов/с на хост (реальные, несэмплированные единицы). Обязателен, > 0.",
    "thresholds.mbps": "Порог мегабит/с на хост. Обязателен, > 0.",
    "thresholds.flows_per_sec": "Порог потоков/с на хост. Обязателен, > 0.",
    "thresholds.tcp_syn_pps": "Необязательный лимит чистых SYN-пакетов/с; 0 или отсутствие отключает.",
    "thresholds.udp_pps": "Необязательный лимит UDP-пакетов/с; 0 или отсутствие отключает.",
    mitigation: "Метод митигации по умолчанию. blackhole отбрасывает весь трафик жертвы; flowspec — точечно; divert уводит трафик в центр очистки.",
    "bgp.local_asn": "Локальный BGP AS-номер Kapkan.",
    "bgp.router_id": "BGP router ID; должен быть IPv4 в формате a.b.c.d.",
    "bgp.next_hop": "IPv4 next-hop для blackhole (discard).",
    "bgp.next_hop6": "IPv6 next-hop для blackhole (нужен, если защищается и блэкхолится IPv6).",
    "bgp.community": "RTBH-community, которое принимает ваш аплинк, вида ASN:value.",
    "bgp.neighbors.address": "Адрес eBGP-соседа.",
    "bgp.graceful_restart.enabled": "Анонсировать BGP Graceful Restart, чтобы сосед СОХРАНЯЛ маршруты митигации Kapkan при перезапуске (напр. при обновлении), а не сбрасывал их. Включено по умолчанию; анонс ничего не стоит для соседа без поддержки. Применяется при (пере)запуске.",
    "bgp.graceful_restart.restart_seconds": "Сколько сосед держит маршруты Kapkan как stale, пока сессия не поднята. 0 — значение по умолчанию (120); максимум 4095.",
    "bgp.graceful_restart.long_lived": "Включить Long-Lived Graceful Restart (RFC 9494), продлевающий хранение сверх restart_seconds. Выключено по умолчанию — долгий LLGR с FlowSpec может вызывать кратковременные петли форвардинга.",
    "bgp.graceful_restart.long_lived_stale_seconds": "Время stale для LLGR в секундах. 0 — значение по умолчанию (3600, 1 ч); максимум 86400 (24 ч).",
    "ban.ttl_seconds": "Каждый анонс автоматически снимается через столько секунд. Постоянных банов нет.",
    "ban.unban_hysteresis_seconds": "Трафик должен держаться ниже порога столько времени до снятия бана (антифлап).",
    "ban.max_active_bans": "Жёсткий лимит одновременных банов; сверх лимита новые отклоняются.",
    "ban.state_file": "Доступный для записи путь, где сохраняются активные баны, чтобы при старте они восстанавливались и переанонсировались — вместе с bgp.graceful_restart это держит митигацию активной при перезапуске. Пусто (по умолчанию) отключает сохранение; unit systemd даёт каталог для записи через StateDirectory=kapkan.",
    "notify.telegram.token_env": "Имя переменной окружения с токеном Telegram-бота (не сам токен).",
    "notify.telegram.chat_id": "ID чата Telegram для отправки алертов (узнать можно через @getmyid_bot).",
    "api.listen": "Адрес прослушивания REST API и метрик (по умолчанию 127.0.0.1:8080).",
    "api.token_env": "Имя переменной окружения с операторским bearer-токеном.",
    "update_check.enabled": "Опциональная проверка новой версии Kapkan через GitHub Releases API. Выключена по умолчанию (нет исходящего трафика); текущая версия всегда доступна локально. Применяется при (пере)запуске.",
    "update_check.interval_seconds": "Интервал опроса для проверки обновлений. 0 — значение по умолчанию (21600, 6 ч); минимум 3600 (1 ч).",
    "update_check.channel": "Какие релизы учитывать: «stable» (последний не-prerelease) или «prerelease» (включая -rc-теги).",
    "update_check.url": "Переопределить endpoint релизов (зеркало/прокси). Пусто — публичный URL GitHub API выводится из channel.",
    "update_check.notify": "Также слать «доступно обновление» через настроенные каналы уведомлений (Telegram/webhook/Slack/email) при первом обнаружении новой версии.",
  },
  de: {
    dry_run: "Wenn aktiv (Standard, auch bei fehlendem Schlüssel), wird Mitigation simuliert und nie angekündigt. Lassen Sie es an, bis die Erkennung an Live-Telemetrie validiert ist.",
    "listen.sflow": 'UDP-Adresse für sFlow, z. B. ":6343". Mindestens eines von sflow/netflow ist nötig.',
    "listen.netflow": 'UDP-Adresse für NetFlow v5/v9 und IPFIX (gemeinsamer Socket), z. B. ":2055".',
    "sampling.default_rate": "Sampling-Rate, wenn ein Exporter seine eigene nicht meldet. Ein Fehler hier skaliert JEDEN Schwellenwert — setzen Sie, was Ihre Router tatsächlich exportieren.",
    networks: "Geschützte Präfixe. Erkennung gilt nur innerhalb davon; sie dürfen sich nicht überlappen.",
    protected_whitelist: "Adressen, die nie gebannt werden, unabhängig vom Verkehr (Gateways, Nameserver).",
    "thresholds.pps": "Pakete/s-Schwelle pro Host (reale, ungesampelte Einheiten). Erforderlich, > 0.",
    "thresholds.mbps": "Megabit/s-Schwelle pro Host. Erforderlich, > 0.",
    "thresholds.flows_per_sec": "Flows/s-Schwelle pro Host. Erforderlich, > 0.",
    "thresholds.tcp_syn_pps": "Optionales Limit für reine SYN-Pakete/s; 0 oder fehlend deaktiviert es.",
    "thresholds.udp_pps": "Optionales Limit für UDP-Pakete/s; 0 oder fehlend deaktiviert es.",
    mitigation: "Standard-Mitigationsmethode. blackhole verwirft den gesamten Opferverkehr; flowspec ist chirurgisch; divert leitet zum Scrubbing-Center um.",
    "bgp.local_asn": "Lokale BGP-AS-Nummer von Kapkan.",
    "bgp.router_id": "BGP-Router-ID; muss eine IPv4 im Format a.b.c.d sein.",
    "bgp.next_hop": "IPv4-Next-Hop für Blackhole (Discard).",
    "bgp.next_hop6": "IPv6-Next-Hop für Blackhole (nötig, wenn IPv6 geschützt und geblackholt wird).",
    "bgp.community": "RTBH-Community, die Ihr Upstream akzeptiert, als ASN:Wert.",
    "bgp.neighbors.address": "Adresse des eBGP-Nachbarn.",
    "bgp.graceful_restart.enabled": "BGP Graceful Restart ankündigen, damit ein Peer Kapkans Mitigation-Routen über einen Neustart hinweg BEHÄLT (z. B. bei einem Upgrade), statt sie zu verwerfen. Standardmäßig an; die Ankündigung kostet nichts gegenüber einem Peer ohne Unterstützung. Wirkt beim (Neu-)Start.",
    "bgp.graceful_restart.restart_seconds": "Wie lange der Peer Kapkans Routen als stale hält, während die Session unten ist. 0 nutzt den Standard (120); maximal 4095.",
    "bgp.graceful_restart.long_lived": "Long-Lived Graceful Restart (RFC 9494) aktivieren, das die Aufbewahrung über restart_seconds hinaus verlängert. Standardmäßig aus — langes LLGR mit FlowSpec kann kurzzeitige Weiterleitungsschleifen verursachen.",
    "bgp.graceful_restart.long_lived_stale_seconds": "LLGR-Stale-Zeit in Sekunden. 0 nutzt den Standard (3600, 1 h); maximal 86400 (24 h).",
    "ban.ttl_seconds": "Jede Ankündigung wird nach so vielen Sekunden automatisch zurückgezogen. Keine dauerhaften Bans.",
    "ban.unban_hysteresis_seconds": "Der Verkehr muss so lange unter der Schwelle bleiben, bevor ein Ban aufgehoben wird (Anti-Flapping).",
    "ban.max_active_bans": "Hartes Limit gleichzeitiger Bans; darüber hinaus werden neue abgelehnt.",
    "ban.state_file": "Beschreibbarer Pfad, in dem aktive Bans persistiert werden, sodass sie beim Start wiederhergestellt und neu angekündigt werden — zusammen mit bgp.graceful_restart bleibt die Mitigation über einen Neustart hinweg aktiv. Leer (Standard) deaktiviert die Persistenz; die systemd-Unit stellt über StateDirectory=kapkan ein beschreibbares Verzeichnis bereit.",
    "notify.telegram.token_env": "Name der Umgebungsvariable mit dem Telegram-Bot-Token (nicht das Token selbst).",
    "notify.telegram.chat_id": "Telegram-Chat-ID für Alerts (per @getmyid_bot ermittelbar).",
    "api.listen": "Listen-Adresse für REST-API und Metriken (Standard 127.0.0.1:8080).",
    "api.token_env": "Name der Umgebungsvariable mit einem Operator-Bearer-Token.",
    "update_check.enabled": "Opt-in-Prüfung auf eine neuere Kapkan-Version über die GitHub-Releases-API. Standardmäßig aus (kein ausgehender Verkehr); die laufende Version ist lokal stets sichtbar. Wirkt beim (Neu-)Start.",
    "update_check.interval_seconds": "Abfrageintervall für die Update-Prüfung. 0 nutzt den Standard (21600, 6 h); Minimum 3600 (1 h).",
    "update_check.channel": "Welche Releases zählen: „stable“ (neuestes Nicht-Prerelease) oder „prerelease“ (inkl. -rc-Tags).",
    "update_check.url": "Releases-Endpunkt überschreiben (Mirror/Proxy). Leer leitet die öffentliche GitHub-API-URL aus channel ab.",
    "update_check.notify": "Beim ersten Erkennen einer neuen Version zusätzlich „Update verfügbar“ über die konfigurierten Benachrichtigungskanäle (Telegram/Webhook/Slack/E-Mail) senden.",
  },
  fr: {
    dry_run: "Si activé (par défaut, y compris clé absente), l'atténuation est simulée et jamais annoncée. Gardez-le activé jusqu'à validation de la détection sur la télémétrie réelle.",
    "listen.sflow": 'Adresse UDP d\'écoute pour sFlow, p. ex. ":6343". Au moins un de sflow/netflow est requis.',
    "listen.netflow": 'Adresse UDP pour NetFlow v5/v9 et IPFIX (socket partagé), p. ex. ":2055".',
    "sampling.default_rate": "Taux d'échantillonnage supposé quand un exporteur ne signale pas le sien. Une erreur ici met à l'échelle TOUS les seuils — mettez ce que vos routeurs exportent réellement.",
    networks: "Préfixes protégés. La détection ne s'applique qu'à l'intérieur ; ils ne doivent pas se chevaucher.",
    protected_whitelist: "Adresses jamais bannies, quel que soit le trafic (passerelles, serveurs de noms).",
    "thresholds.pps": "Seuil paquets/s par hôte (unités réelles, non échantillonnées). Requis, > 0.",
    "thresholds.mbps": "Seuil mégabits/s par hôte. Requis, > 0.",
    "thresholds.flows_per_sec": "Seuil flux/s par hôte. Requis, > 0.",
    "thresholds.tcp_syn_pps": "Limite optionnelle de paquets SYN purs/s ; 0 ou absent la désactive.",
    "thresholds.udp_pps": "Limite optionnelle de paquets UDP/s ; 0 ou absent la désactive.",
    mitigation: "Méthode d'atténuation par défaut. blackhole supprime tout le trafic de la victime ; flowspec est chirurgical ; divert envoie vers un centre de nettoyage.",
    "bgp.local_asn": "Numéro d'AS BGP local de Kapkan.",
    "bgp.router_id": "Router ID BGP ; doit être une IPv4 au format a.b.c.d.",
    "bgp.next_hop": "Next-hop IPv4 pour le blackhole (discard).",
    "bgp.next_hop6": "Next-hop IPv6 pour le blackhole (requis si de l'IPv6 est protégé et blackholé).",
    "bgp.community": "Communauté RTBH acceptée par votre transit, sous forme ASN:valeur.",
    "bgp.neighbors.address": "Adresse du voisin eBGP.",
    "bgp.graceful_restart.enabled": "Annoncer BGP Graceful Restart pour qu'un voisin CONSERVE les routes d'atténuation de Kapkan lors d'un redémarrage (p. ex. une mise à niveau) au lieu de les purger. Activé par défaut ; l'annonce ne coûte rien face à un voisin qui ne le prend pas en charge. Prend effet au (re)démarrage.",
    "bgp.graceful_restart.restart_seconds": "Durée pendant laquelle le voisin garde les routes de Kapkan comme stale tant que la session est coupée. 0 utilise la valeur par défaut (120) ; plafonné à 4095.",
    "bgp.graceful_restart.long_lived": "Activer Long-Lived Graceful Restart (RFC 9494), prolongeant la rétention au-delà de restart_seconds. Désactivé par défaut — un long LLGR avec FlowSpec peut provoquer des boucles de transfert transitoires.",
    "bgp.graceful_restart.long_lived_stale_seconds": "Temps stale LLGR en secondes. 0 utilise la valeur par défaut (3600, 1 h) ; plafonné à 86400 (24 h).",
    "ban.ttl_seconds": "Chaque annonce se retire automatiquement après ce nombre de secondes. Pas de bans permanents.",
    "ban.unban_hysteresis_seconds": "Le trafic doit rester sous le seuil pendant ce temps avant la levée d'un ban (anti-battement).",
    "ban.max_active_bans": "Plafond strict de bans simultanés ; au-delà, les nouveaux sont refusés.",
    "ban.state_file": "Chemin accessible en écriture où les bans actifs sont persistés, afin d'être réhydratés et réannoncés au démarrage — couplé à bgp.graceful_restart, cela maintient l'atténuation lors d'un redémarrage. Vide (par défaut) désactive la persistance ; l'unité systemd fournit un répertoire en écriture via StateDirectory=kapkan.",
    "notify.telegram.token_env": "Nom de la variable d'environnement contenant le token du bot Telegram (jamais le token).",
    "notify.telegram.chat_id": "ID de chat Telegram où poster les alertes (à trouver via @getmyid_bot).",
    "api.listen": "Adresse d'écoute de l'API REST et des métriques (défaut 127.0.0.1:8080).",
    "api.token_env": "Nom de la variable d'environnement contenant un token bearer opérateur.",
    "update_check.enabled": "Vérification optionnelle d'une nouvelle version de Kapkan via l'API GitHub Releases. Désactivée par défaut (aucun trafic sortant) ; la version en cours reste toujours exposée localement. Prend effet au (re)démarrage.",
    "update_check.interval_seconds": "Intervalle d'interrogation pour la vérification des mises à jour. 0 utilise la valeur par défaut (21600, 6 h) ; minimum 3600 (1 h).",
    "update_check.channel": "Quelles versions comptent : « stable » (dernière non-prerelease) ou « prerelease » (inclut les tags -rc).",
    "update_check.url": "Remplacer l'endpoint des releases (miroir/proxy). Vide déduit l'URL publique de l'API GitHub depuis channel.",
    "update_check.notify": "Envoyer aussi « mise à jour disponible » via les canaux de notification configurés (Telegram/webhook/Slack/e-mail) à la première détection d'une nouvelle version.",
  },
  es: {
    dry_run: "Si está activo (por defecto, incluso sin la clave), la mitigación se simula y nunca se anuncia. Mantenlo activado hasta validar la detección con telemetría real.",
    "listen.sflow": 'Dirección UDP de escucha para sFlow, p. ej. ":6343". Se requiere al menos uno de sflow/netflow.',
    "listen.netflow": 'Dirección UDP para NetFlow v5/v9 e IPFIX (socket compartido), p. ej. ":2055".',
    "sampling.default_rate": "Tasa de muestreo asumida cuando un exportador no informa la suya. Un error aquí escala TODOS los umbrales — pon lo que tus routers exportan realmente.",
    networks: "Prefijos protegidos. La detección solo aplica dentro de ellos; no deben solaparse.",
    protected_whitelist: "Direcciones que nunca se banean, sin importar el tráfico (gateways, servidores de nombres).",
    "thresholds.pps": "Umbral de paquetes/s por host (unidades reales, sin muestrear). Obligatorio, > 0.",
    "thresholds.mbps": "Umbral de megabits/s por host. Obligatorio, > 0.",
    "thresholds.flows_per_sec": "Umbral de flujos/s por host. Obligatorio, > 0.",
    "thresholds.tcp_syn_pps": "Límite opcional de paquetes SYN puros/s; 0 o ausente lo desactiva.",
    "thresholds.udp_pps": "Límite opcional de paquetes UDP/s; 0 o ausente lo desactiva.",
    mitigation: "Método de mitigación por defecto. blackhole descarta todo el tráfico de la víctima; flowspec es quirúrgico; divert lo desvía a un centro de limpieza.",
    "bgp.local_asn": "Número de AS BGP local de Kapkan.",
    "bgp.router_id": "Router ID de BGP; debe ser una IPv4 en formato a.b.c.d.",
    "bgp.next_hop": "Next-hop IPv4 para el blackhole (descarte).",
    "bgp.next_hop6": "Next-hop IPv6 para el blackhole (necesario si se protege y blackholea IPv6).",
    "bgp.community": "Comunidad RTBH que acepta tu upstream, como ASN:valor.",
    "bgp.neighbors.address": "Dirección del vecino eBGP.",
    "bgp.graceful_restart.enabled": "Anunciar BGP Graceful Restart para que un vecino CONSERVE las rutas de mitigación de Kapkan durante un reinicio (p. ej. una actualización) en lugar de descartarlas. Activado por defecto; anunciarlo no cuesta nada frente a un vecino que no lo admite. Surte efecto al (re)iniciar.",
    "bgp.graceful_restart.restart_seconds": "Cuánto tiempo el vecino mantiene las rutas de Kapkan como stale mientras la sesión está caída. 0 usa el valor por defecto (120); máximo 4095.",
    "bgp.graceful_restart.long_lived": "Activar Long-Lived Graceful Restart (RFC 9494), que extiende la retención más allá de restart_seconds. Desactivado por defecto — un LLGR largo con FlowSpec puede causar bucles de reenvío transitorios.",
    "bgp.graceful_restart.long_lived_stale_seconds": "Tiempo stale de LLGR en segundos. 0 usa el valor por defecto (3600, 1 h); máximo 86400 (24 h).",
    "ban.ttl_seconds": "Cada anuncio se retira automáticamente tras estos segundos. No hay baneos permanentes.",
    "ban.unban_hysteresis_seconds": "El tráfico debe quedar bajo el umbral este tiempo antes de retirar un baneo (anti-aleteo).",
    "ban.max_active_bans": "Tope estricto de baneos simultáneos; por encima, los nuevos se rechazan.",
    "ban.state_file": "Ruta con permiso de escritura donde se persisten los baneos activos, para rehidratarlos y reanunciarlos al arrancar — junto con bgp.graceful_restart mantiene la mitigación durante un reinicio. Vacío (por defecto) desactiva la persistencia; la unidad systemd proporciona un directorio escribible vía StateDirectory=kapkan.",
    "notify.telegram.token_env": "Nombre de la variable de entorno con el token del bot de Telegram (nunca el token).",
    "notify.telegram.chat_id": "ID del chat de Telegram donde publicar alertas (búscalo con @getmyid_bot).",
    "api.listen": "Dirección de escucha de la API REST y métricas (por defecto 127.0.0.1:8080).",
    "api.token_env": "Nombre de la variable de entorno con un token bearer de operador.",
    "update_check.enabled": "Comprobación opcional de una versión más nueva de Kapkan vía la API de GitHub Releases. Desactivada por defecto (sin tráfico saliente); la versión en ejecución siempre se expone localmente. Surte efecto al (re)iniciar.",
    "update_check.interval_seconds": "Intervalo de sondeo para la comprobación de actualizaciones. 0 usa el valor por defecto (21600, 6 h); mínimo 3600 (1 h).",
    "update_check.channel": "Qué versiones cuentan: «stable» (última no-prerelease) o «prerelease» (incluye etiquetas -rc).",
    "update_check.url": "Sobrescribir el endpoint de releases (espejo/proxy). Vacío deriva la URL pública de la API de GitHub desde channel.",
    "update_check.notify": "Enviar también «actualización disponible» por los canales de notificación configurados (Telegram/webhook/Slack/email) la primera vez que se detecta una nueva versión.",
  },
};
